### ISSUE TITLE
ValueError: could not convert string to float

### ISSUE THREAD

**Issue by leto1210** [leto1210/OpenCorsairLink-Netdata#1]
/opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace opencorsairlink
2018-05-06 15:11:01: python.d INFO: plugin: main: Using python 2
2018-05-06 15:11:01: python.d DEBUG: plugin: main: module load source: 'opencorsairlink' => [OK]
2018-05-06 15:11:01: python.d DEBUG: plugin: main: module load config: 'opencorsairlink' => [OK]
2018-05-06 15:11:01: python.d DEBUG: plugin: main: job initialization: 'opencorsairlink opencorsairlink' => ['OK']
2018-05-06 15:11:01: python.d DEBUG: plugin: main: module status: 'opencorsairlink' => [OK] (jobs: 1)
2018-05-06 15:11:01: python.d DEBUG: opencorsairlink: opencorsairlink: raw_data: <<[u'Dev=0, CorsairLink Device Found: HX750i!\n', u'\n', u'Vendor: CORSAIR\n', u'Product: HX750i\n', u'Firmware: NA\n', u'Temperature 0: 42.48 C\n', u'Temperature 1: 37.10 C\n', u'Powered: 2567338 (29d. 17h)\n', u'Uptime: 421738 (4d. 21h)\n', u'Supply Voltage: 230.00 V\n', u'Total Watts: 92.00 W\n', u'Output 12v:\n', u'\tVoltage 12.06 V\n', u'\tAmps 5.00 A\n', u'\tWatts 56.00 W\n', u'Output 5v:\n', u'\tVoltage 5.00 V\n', u'\tAmps 5.00 A\n', u'\tWatts 25.00 W\n', u'Output 3.3v:\n', u'\tVoltage 3.34 V\n', u'\tAmps 1.88 A\n', u'\tWatts 6.00 W\n']>>
2018-05-06 15:11:01: python.d DEBUG: opencorsairlink: opencorsairlink: ==================================
2018-05-06 15:11:01: python.d DEBUG: opencorsairlink: opencorsairlink: l: <<Dev=0, CorsairLink Device Found: HX750i!>>
2018-05-06 15:11:01: python.d DEBUG: opencorsairlink: opencorsairlink: l: <<>>
2018-05-06 15:11:01: python.d DEBUG: opencorsairlink: opencorsairlink: l: <<Vendor: CORSAIR>>
2018-05-06 15:11:01: python.d DEBUG: opencorsairlink: opencorsairlink: l: <<Product: HX750i>>
2018-05-06 15:11:01: python.d DEBUG: opencorsairlink: opencorsairlink: l: <<Firmware: NA>>
2018-05-06 15:11:01: python.d DEBUG: opencorsairlink: opencorsairlink: l: <<Temperature 0: 42.48 C>>
2018-05-06 15:11:01: python.d DEBUG: opencorsairlink: opencorsairlink: l: <<Temperature 1: 37.10 C>>
2018-05-06 15:11:01: python.d DEBUG: opencorsairlink: opencorsairlink: l: <<Powered: 2567338 (29d. 17h)>>
2018-05-06 15:11:01: python.d DEBUG: opencorsairlink: opencorsairlink: l: <<Uptime: 421738 (4d. 21h)>>
2018-05-06 15:11:01: python.d DEBUG: opencorsairlink: opencorsairlink: l: <<Supply Voltage: 230.00 V>>
2018-05-06 15:11:01: python.d DEBUG: opencorsairlink: opencorsairlink: l: <<Total Watts: 92.00 W>>
2018-05-06 15:11:01: python.d DEBUG: opencorsairlink: opencorsairlink: l: <<Output 12v:>>
2018-05-06 15:11:01: python.d DEBUG: opencorsairlink: opencorsairlink: l: <<Voltage 12.06 V>>
2018-05-06 15:11:01: python.d ERROR: opencorsairlink: opencorsairlink: _get_data() failed. Command: ['/usr/bin/OpenCorsairLink.elf', '--device', '0']. Error: could not convert string to float: V
2018-05-06 15:11:01: python.d ERROR: opencorsairlink: opencorsairlink: Traceback (most recent call last):
File "/opt/netdata/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/ExecutableService.py", line 79, in check
data = self._get_data()
File "/opt/netdata/usr/libexec/netdata/python.d/opencorsairlink.chart.py", line 109, in get_data
data['out%s_v' % lm] = int( float(fields[-1]) * 100)
ValueError: could not convert string to float: V

2018-05-06 15:11:01: python.d INFO: opencorsairlink: opencorsairlink: check() => [FAILED]
2018-05-06 15:11:01: python.d INFO: plugin: main: FINISHED

**Comment by leto1210** [comment]
sudo /usr/bin/OpenCorsairLink.elf --device 0
Dev=0, CorsairLink Device Found: HX750i!

Vendor: CORSAIR
Product: HX750i
Firmware: NA
Temperature 0: 42.48 C
Temperature 1: 37.10 C
Powered: 2576906 (29d. 19h)
Uptime: 2906 (0d. 0h)
Supply Voltage: 230.00 V
Total Watts: 84.00 W
Output 12v:
Voltage 12.03 V
Amps 4.50 A
Watts 56.00 W
Output 5v:
Voltage 5.00 V
Amps 4.88 A
Watts 24.00 W
Output 3.3v:
Voltage 3.34 V
Amps 1.88 A
Watts 6.00 W
